name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and start containers
      run: docker-compose up -d --build

    - name: Run migrations
      run: docker-compose exec django python manage.py migrate

    - name: Run tests
      run: docker-compose exec django python manage.py test

    - name: Check database connection
      run: docker-compose exec django python manage.py dbshell -c "SELECT 1;"

    - name: Stop containers
      if: always()
      run: docker-compose down