name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Docker Compose (using Buildx)
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Build and start containers
      run: docker compose up -d --build # Use 'docker compose' instead of 'docker-compose'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: docker compose exec django python manage.py migrate # Use 'docker compose'

    - name: Run tests
      run: docker compose exec django python manage.py test weather_app # Use 'docker compose'

    - name: Check database connection
      run: |
        docker compose exec django python manage.py shell -c "
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute('SELECT 1;')
        result = cursor.fetchone()
        print('Database connection successful:', result)
    "

    - name: Stop containers
      if: always()
      run: docker compose down # Use 'docker compose'